### PR TITLE
Base64 encode serialized jobs when using Postgres

### LINKED ISSUE #42: [Postgresql] Serialization/Unserialization error while using non-public fields on jobs
Hi, I recently started using this package but stumbled upon an issue around non-public fields on jobs. 

If a job has a non-public field PHP \unserialize function places a `\0\0` value in front of it. When this serialized string is transferred into DB and it is accepted as a null-terminated string and as expected half of it is missing. So when this package tries to unserialize the string, it does not work. 

Currently, I made them public to overcome the issue but another solution might be possible. I thought about SerializesModels but, trait usage can not be checked against. So don't really know about it.

Currently, I don't have the repro but if requested I can whip something up.

laravel/framework v8.83.4
ksassnowski/venture 3.5.0
php8.1
Postgres 12

### PR DESCRIPTION
**Pull request by ksassnowski**
Fixes #42

This PR fixes a bug where serializing workflow jobs with private properties could lead to truncated data being saved when using Postgresql.

Since we serialize and unserialize workflow jobs in multiple places (the `Workflow` model, as well as the `UnserializeWorkflowJobExtractor`), I decided to separate this logic out into a separate class so it isn't duplicated all over the place. 

In short, when serializing workflow job, we check if we’re using a `PostgresConnection` and if so `base64_encode` the serialized string before storing it. This gets rid of any null bytes in the serialized string so Postgres doesn’t treat it as a null-terminated string anymore. We do the inverse when unserializing jobs. To ensure backwards compatibility, we don't `base64_decode` a string if it doesn't contain `:` or `;`. We use this as a heuristic to check if we're dealing with a base64 encoded string or not since these characters will never appear in a base64 encoded string. This implementation is based on the PR which fixes the same bug in Laravel’s queue system (https://github.com/laravel/framework/pull/36081).

I haven’t added a separate test to test for this specific bug, as adding configuring a Postgres database in our CI pipeline just for a single test seemed a little excessive. I did, however, reproduce the bug locally and confirmed that these changes fix the bug. I used the example repository provided in #42 as starting point.

As far as I can tell, this change should be backwards compatible and should not require a major version bump.

### CODE REVIEW

File: src/Serializer/DefaultSerializer.php [hunk 1]
```diff
@@ -0,0 +1,35 @@
...
+ * the LICENSE file that was distributed with this source code.
+ *
+ * @see https://github.com/ksassnowski/venture
+ */
+
+namespace Sassnowski\Venture\Serializer;
+
+use Laravel\SerializableClosure\Serializers\UnserializeException;
+
+final class DefaultSerializer implements WorkflowJobSerializer
```
Comment (stevebauman) [inline src/Serializer/DefaultSerializer.php:18]: Is the default serializer needed since the `Base64WorkflowSerializer` operates the same except when dealing with Postgre connections?

**Review by stevebauman — APPROVED** [review]

File: src/Serializer/Base64WorkflowSerializer.php [hunk 2]
```diff
@@ -0,0 +1,55 @@
...
+ */
+
+namespace Sassnowski\Venture\Serializer;
+
+use Illuminate\Database\ConnectionInterface;
+use Illuminate\Database\PostgresConnection;
+use Illuminate\Support\Str;
+use Laravel\SerializableClosure\Serializers\UnserializeException;
+
+final class Base64WorkflowSerializer implements WorkflowJobSerializer
```
Comment (stevebauman) [inline src/Serializer/Base64WorkflowSerializer.php:21]: `final`

image

File: src/Serializer/DefaultSerializer.php (hunk 1 above)
Comment (ksassnowski) [reply src/Serializer/DefaultSerializer.php:18]: That mostly exists for testing purposes so we don’t have to fiddle around with connection objects everywhere we depend on a serializer. I started calling it `FakeSerializer` but realized it doesn’t actually fake anything 😅

Comment (stevebauman) [reply src/Serializer/DefaultSerializer.php:18]: Ohh okay understandable! Sounds good 👍
